-- CREATE TRIGGER FOR AUTO-GENERATED IDS
CREATE OR REPLACE TRIGGER LMS_AUTHORS_TRIGGER
BEFORE INSERT ON LMS_AUTHORS
FOR EACH ROW
BEGIN
    SELECT AUTHOR_ID_SEQ.NEXTVAL INTO :NEW.AUTHOR_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER LMS_BOOKS_TRIGGER
BEFORE INSERT ON LMS_BOOKS
FOR EACH ROW
BEGIN
    SELECT BOOK_ID_SEQ.NEXTVAL INTO :NEW.BOOK_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER LMS_MEMBERS_TRIGGER
BEFORE INSERT ON LMS_MEMBERS
FOR EACH ROW
BEGIN
    SELECT MEMBER_ID_SEQ.NEXTVAL INTO :NEW.MEMBER_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER LMS_BORROWEDBOOKS_TRIGGER
BEFORE INSERT ON LMS_BORROWEDBOOKS
FOR EACH ROW
BEGIN
    SELECT BORROW_ID_SEQ.NEXTVAL INTO :NEW.BORROW_ID FROM DUAL;
END;