-- CREATE SEQUENCE FOR AUTO-GENERATED IDS
--DROP SEQUENCE AUTHOR_ID_SEQ;
CREATE SEQUENCE AUTHOR_ID_SEQ START WITH 100 INCREMENT BY 1;
/
--DROP SEQUENCE BOOK_ID_SEQ;
CREATE SEQUENCE BOOK_ID_SEQ START WITH 100 INCREMENT BY 1;
/
--DROP SEQUENCE MEMBER_ID_SEQ;
CREATE SEQUENCE MEMBER_ID_SEQ START WITH 100 INCREMENT BY 1;
/
--DROP SEQUENCE BORROW_ID_SEQ;
CREATE SEQUENCE BORROW_ID_SEQ START WITH 100 INCREMENT BY 1;
/
--DROP SEQUENCE ERROR_ID_SEQ;
CREATE SEQUENCE ERROR_ID_SEQ START WITH 100 INCREMENT BY 1;
/
SELECT ERROR_ID_SEQ.NEXTVAL FROM DUAL;
SELECT AUTHOR_ID_SEQ.NEXTVAL FROM DUAL;
SELECT BOOK_ID_SEQ.NEXTVAL FROM DUAL;
SELECT MEMBER_ID_SEQ.NEXTVAL FROM DUAL;
SELECT BORROW_ID_SEQ.NEXTVAL FROM DUAL;
