DROP TABLE LMS_AUTHORS;
-- CREATE LMS_AUTHORS TABLE
CREATE TABLE LMS_AUTHORS
  (
    AUTHOR_ID   NUMBER,
    AUTHOR_CODE VARCHAR2(25),
    FNAME       VARCHAR2(50) NOT NULL,
    LNAME       VARCHAR2(50) NOT NULL,
    MAIL_ID     VARCHAR2(50) NOT NULL,
    COUNTRY     VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_LMS_AUTHORS PRIMARY KEY (AUTHOR_ID),
    CONSTRAINT UQ_AUTHOR_CODE UNIQUE (AUTHOR_CODE),
    CONSTRAINT UNIQUE_FNAME_LNAME UNIQUE (FNAME, LNAME)
  );
--ALTER TABLE LMS_AUTHORS ADD  AUTHOR_CODE VARCHAR2(25) NOT NULL;
/
 DROP TABLE LMS_BOOKS;
-- CREATE LMS_BOOKS TABLE WITH AUTHOR RELATIONSHIP
CREATE TABLE LMS_BOOKS
  (
    BOOK_ID    NUMBER,
    AUTHOR_ID  NUMBER NOT NULL,
    AUTHOR_CODE VARCHAR2(25),
    TITLE      VARCHAR2(100) NOT NULL,
    BOOK_GENER VARCHAR2(100),
    CONSTRAINT PK_LMS_BOOKS PRIMARY KEY (BOOK_ID),
    CONSTRAINT FK_LMS_BOOKS_AUTHORS FOREIGN KEY (AUTHOR_ID) REFERENCES LMS_AUTHORS(AUTHOR_ID),
    CONSTRAINT FK_LMS_BOOKS_ATHR_CODE FOREIGN KEY (AUTHOR_CODE) REFERENCES LMS_AUTHORS(AUTHOR_CODE)
  );
ALTER TABLE LMS_BOOKS ADD PUBLISH_YEAR NUMBER; --added
ALTER TABLE LMS_BOOKS ADD STATUS CHAR DEFAULT 'Y';--added
ALTER TABLE LMS_BOOKS ADD BOOK_NOS NUMBER DEFAULT 1 ; --added
ALTER TABLE LMS_BOOKS ADD CONSTRAINT UK_LMS_BOOK_TITLE UNIQUE (TITLE); --added
/
 DROP TABLE LMS_MEMBERS;
-- CREATE LMS_MEMBERS TABLE
CREATE TABLE LMS_MEMBERS
  (
    MEMBER_ID   NUMBER,
    FNAME       VARCHAR2(50) NOT NULL,
    LNAME       VARCHAR2(50) NOT NULL,
    MOBILE_NO   VARCHAR2(14) NOT NULL,
    MAIL_ID     VARCHAR2(100),
    MEMBER_CODE VARCHAR2 (100),
    CONSTRAINT PK_LMS_MEMBERS PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UNIQUE_LMS_FLNAME  UNIQUE (FNAME, LNAME),
    CONSTRAINT UNIQUE_LMS_MBRCODE UNIQUE (MEMBER_CODE)
  );
/
DROP TABLE LMS_BORROWEDBOOKS;
-- CREATE LMS_BORROWEDBOOKS TABLE WITH MEMBER AND BOOK RELATIONSHIPS
CREATE TABLE LMS_BORROWEDBOOKS
  (
    BORROW_ID   NUMBER,
    MEMBER_ID   NUMBER NOT NULL,
    BOOK_ID     NUMBER NOT NULL,
    AUTHOR_CODE VARCHAR2(25) ,
    MEMBER_CODE VARCHAR2(100),
    ISSUE_DATE DATE,
    RETURN_DATE DATE,
    CONSTRAINT PK_LMS_BORROWEDBOOKS PRIMARY KEY (BORROW_ID),
    CONSTRAINT FK_LMS_BORROWEDBOOKS_AUTHORS FOREIGN KEY (AUTHOR_CODE) REFERENCES LMS_AUTHORS(AUTHOR_CODE),
    CONSTRAINT FK_LMS_BORROWEDBOOKS_MEMBERS FOREIGN KEY (MEMBER_ID)   REFERENCES LMS_MEMBERS(MEMBER_ID),
    CONSTRAINT FK_LMS_BORROWEDBOOKS_BOOKS FOREIGN KEY   (BOOK_ID)     REFERENCES LMS_BOOKS(BOOK_ID),
    CONSTRAINT FK_LMS_BORROWEDBOOKS_MBRCODE FOREIGN KEY (MEMBER_CODE )REFERENCES LMS_MEMBERS(MEMBER_CODE)
  );
/
DROP TABLE LMS_ERRORLOGS;
-- CREATE ERROR_LOG TABLE
CREATE TABLE LMS_ERRORLOGS
  (
    ERROR_ID        NUMBER,
    ERROR_CODE      VARCHAR2(20),
    ERROR_MESSAGE   VARCHAR2(255),
    ERROR_TIMESTAMP TIMESTAMP,
    CONSTRAINT PK_ERROR_LOG PRIMARY KEY (ERROR_ID)
  );
-- ALTER TABLE LMS_ERRORLOGS ADD  ERROR_CODE VARCHAR2(20) NOT NULL;
/
SELECT * FROM LMS_AUTHORS;
/
SELECT * FROM LMS_BOOKS;
/
SELECT * FROM LMS_MEMBERS;
/
SELECT * FROM LMS_MEMBERS;
/
SELECT * FROM LMS_BORROWEDBOOKS;
/
SELECT * FROM LMS_ERRORLOGS;


