
--INSERTING into LMS_AUTHORS

Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10001,'ATHR10001','SAROJINI','NAIDU','sarojini.naidu@gmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10002,'ATHR10002','DURJOY','DATTA','durjoy.datta@rediffmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10003,'ATHR10003','PREETI','SHENOY','preeti.shenoy@gmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10004,'ATHR10004','AJAY K.','PANDEY','ajayk.pandey@gmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10005,'ATHR10005','ANUJA','CHAUHAN','anuja.chauhan@rediffmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10006,'ATHR10006','RAVINDER','SINGH','ravinder.singh@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10007,'ATHR10007','SANDHYA','MENON','sandhya.menon@rediffmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10008,'ATHR10008','SONALI','DEV','sonali.dev@gmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10009,'ATHR10009','ANURAG','GARG','anurag.garg@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10010,'ATHR10010','VIKRANT','KHANNA','vikrant.khanna@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10011,'ATHR10011','SUDEEP','NAGARKAR','sudeep.nagarkar@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10012,'ATHR10012','CHETAN','BHAGAT','chetan.bhagat@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10013,'ATHR10013','SUDHIR','NAIR','sudhir.nair@gmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10014,'ATHR10014','ALISHA','RAI','alisha.rai@rediffmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10015,'ATHR10015','NIKITA','SINGH','nikita.singh@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10016,'ATHR10016','FARAAZ','KAZI','faraaz.kazi@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10017,'ATHR10017','SARITA','VARMA','sarita.varma@rediffmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10018,'ATHR10018','YASHODHARA','LAL','yashodhara.lal@rediffmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10019,'ATHR10019','SMITA','SHETTY','smita.shetty@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10020,'ATHR10020','APJ ABDUL','KALAM','apjabdul.kalam@yahoo.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10021,'ATHR10021','RAJAT KUMAR','SWAIN','rajatkumar.swain@rediffmail.com','INDIA');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10023,'ATHR10023','TANVI','SHINA','tanvi.shina@gmail.com','NEED TO UPDATE');
Insert into LMS_AUTHORS (AUTHOR_ID,AUTHOR_CODE,FNAME,LNAME,MAIL_ID,COUNTRY) values (10024,'ATHR10024','BALLI KAUR','JASWAL','ballikaur.jaswal@gmail.com','NEED TO UPDATE');

/
